[package]
name = "jni_example"
version = "0.1.0"
authors = ["Wang Xuerui <git@xen0n.name>"]

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]
jni = "0.4.0"
jni_macros = { path = "../jni_macros", version = "0.1.0" }
