[package]
name = "jni_macros"
version = "0.1.0"
authors = ["Wang Xuerui <git@xen0n.name>"]

[lib]
proc_macro = true

[dependencies]
quote = "0.3.15"
syn = { version = "0.11.10", features = ["full"] }
